# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm run install:deps
      - name: (tree-chart-core)Build
        working-directory: packages/tree-chart-core
        run: npm run build
      - name: (vue-tree-chart)Build
        working-directory: packages/vue-tree-chart
        run: npm run build:component
      - name: (tree-chart-demo)Build
        working-directory: packages/tree-chart-demo
        run: npm run build
